[package]
name = "html_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
html_rendering_derive = {path = "./html_rendering_derive"}
chrono = "0.4.19"
chrono-tz = "0.6.1"
